export const mockDB = [
  {
    id: 1,
    name: 'ALLIAR',
    code: 'AALR3',
    category: 'Saúde',
    value: 30,
  },
  {
    id: 2,
    name: 'ABC BRASIL',
    code: 'ABCB4',
    category: 'Financeiro',
    value: 42,
  },
  {
    id: 3,
    name: 'AMBEV SA',
    code: 'ABEV3',
    category: 'Consumo não Cíclico',
    value: 7,
  },
  {
    id: 4,
    name: 'ADVANCED-DH',
    code: 'ADHM3',
    category: 'Saúde',
    value: 40,
  },
  {
    id: 5,
    name: 'AERIS',
    code: 'AERI3',
    category: 'Bens Industriais',
    value: 4,
  },
  {
    id: 6,
    name: 'AES BRASIL',
    code: 'AESB3',
    category: 'Utilidade Pública',
    value: 43,
  },
  {
    id: 7,
    name: 'AESOPERACOES',
    code: 'AESO3',
    category: 'Utilidade Pública',
    value: 24,
  },
  {
    id: 8,
    name: 'AFLUENTE T',
    code: 'AFLT3',
    category: 'Utilidade Pública',
    value: 41,
  },
  {
    id: 9,
    name: 'BRASILAGRO',
    code: 'AGRO3',
    category: 'Consumo não Cíclico',
    value: 39,
  },
  {
    id: 10,
    name: 'AGROGALAXY',
    code: 'AGXY3',
    category: 'Consumo não Cíclico',
    value: 36,
  },
  {
    id: 11,
    name: 'SPTURIS',
    code: 'AHEB3',
    category: 'Consumo Cíclico',
    value: 35,
  },
  {
    id: 12,
    name: 'ALLIED',
    code: 'ALLD3',
    category: 'Consumo Cíclico',
    value: 13,
  },
  {
    id: 13,
    name: 'ALPARGATAS',
    code: 'ALPA3',
    category: 'Consumo Cíclico',
    value: 14,
  },
  {
    id: 14,
    name: 'ESTAPAR',
    code: 'ALPK3',
    category: 'Bens Industriais',
    value: 1,
  },
  {
    id: 15,
    name: 'ALIANSCE',
    code: 'ALSC3',
    category: 'Financeiro',
    value: 13,
  },
  {
    id: 16,
    name: 'ALIANSCSONAE',
    code: 'ALSO3',
    category: 'Financeiro',
    value: 30,
  },
  {
    id: 17,
    name: 'ALUPAR',
    code: 'ALUP11',
    category: 'Utilidade Pública',
    value: 42,
  },
  {
    id: 18,
    name: 'LOJAS MARISA',
    code: 'AMAR11',
    category: 'Consumo Cíclico',
    value: 16,
  },
  {
    id: 19,
    name: 'AMBIPAR',
    code: 'AMBP3',
    category: 'Utilidade Pública',
    value: 11,
  },
  {
    id: 20,
    name: 'AMERICANAS',
    code: 'AMER3',
    category: 'Consumo Cíclico',
    value: 55,
  },
  {
    id: 21,
    name: 'ANIMA',
    code: 'ANIM3',
    category: 'Consumo Cíclico',
    value: 47,
  },
  {
    id: 22,
    name: 'ALPER S.A.',
    code: 'APER1',
    category: 'Financeiro',
    value: 57,
  },
  {
    id: 23,
    name: 'ALIPERTI',
    code: 'APTI3',
    category: 'Consumo não Cíclico',
    value: 29,
  },
  {
    id: 24,
    name: 'ARMAC',
    code: 'ARML3',
    category: 'Bens Industriais',
    value: 37,
  },
  {
    id: 25,
    name: 'AREZZO CO',
    code: 'ARZZ3',
    category: 'Consumo Cíclico',
    value: 12,
  },
  {
    id: 26,
    name: 'ASSAI',
    code: 'ASAI3',
    category: 'Consumo não Cíclico',
    value: 11,
  },
  {
    id: 27,
    name: 'ATMASA',
    code: 'ATMP3',
    category: 'Bens Industriais',
    value: 25,
  },
  {
    id: 28,
    name: 'ATOMPAR',
    code: 'ATOM3',
    category: 'Outros',
    value: 50,
  },
  {
    id: 29,
    name: 'AURA 360',
    code: 'AURA33',
    category: 'Materiais Básicos',
    value: 8,
  },
  {
    id: 30,
    name: 'AUREN',
    code: 'AURE3',
    category: 'Utilidade Pública',
    value: 7,
  },
  {
    id: 31,
    name: 'ALPHAVILLE',
    code: 'AVLL3',
    category: 'Consumo Cíclico',
    value: 39,
  },
  {
    id: 32,
    name: 'AZEVEDO',
    code: 'AZEV3',
    category: 'Bens Industriais',
    value: 56,
  },
  {
    id: 33,
    name: 'AZUL',
    code: 'AZUL4',
    category: 'Bens Industriais',
    value: 7,
  },
  {
    id: 34,
    name: 'B3',
    code: 'B3SA3',
    category: 'Financeiro',
    value: 1,
  },
  {
    id: 35,
    name: 'BAHEMA',
    code: 'BAHI3',
    category: 'Consumo Cíclico',
    value: 52,
  },
  {
    id: 36,
    name: 'BAUMER',
    code: 'BALM3',
    category: 'Saúde',
    value: 42,
  },
  {
    id: 37,
    name: 'EXCELSIOR',
    code: 'BAUH3',
    category: 'Consumo não Cíclico',
    value: 58,
  },
  {
    id: 38,
    name: 'AMAZONIA',
    code: 'BAZA3',
    category: 'Financeiro',
    value: 49,
  },
  {
    id: 39,
    name: 'BRASIL',
    code: 'BBAS3',
    category: 'Financeiro',
    value: 50,
  },
  {
    id: 40,
    name: 'BRADESCO',
    code: 'BBDC3',
    category: 'Financeiro',
    value: 50,
  },
  {
    id: 41,
    name: 'BBMLOGISTICA',
    code: 'BBML3',
    category: 'Bens Industriais',
    value: 43,
  },
  {
    id: 42,
    name: 'BR BROKERS',
    code: 'BBRK3',
    category: 'Financeiro',
    value: 11,
  },
  {
    id: 43,
    name: 'BBSEGURIDADE',
    code: 'BBSE3',
    category: 'Financeiro',
    value: 23,
  },
  {
    id: 44,
    name: 'BARDELLA',
    code: 'BDLL3',
    category: 'Bens Industriais',
    value: 47,
  },
  {
    id: 45,
    name: 'MINERVA',
    code: 'BEEF3',
    category: 'Consumo não Cíclico',
    value: 21,
  },
  {
    id: 46,
    name: 'BANESTES',
    code: 'BEES3',
    category: 'Financeiro',
    value: 27,
  },
  {
    id: 47,
    name: 'BANESE',
    code: 'BGIP3',
    category: 'Financeiro',
    value: 52,
  },
  {
    id: 48,
    name: 'BANCO INTER',
    code: 'BIDI11',
    category: 'Financeiro',
    value: 47,
  },
  {
    id: 49,
    name: 'BIOMM',
    code: 'BIOM12',
    category: 'Saúde',
    value: 57,
  },
  {
    id: 50,
    name: 'BK BRASIL',
    code: 'BKBR3',
    category: 'Consumo Cíclico',
    value: 12,
  },
  {
    id: 51,
    name: 'BLAU',
    code: 'BLAU3',
    category: 'Saúde',
    value: 42,
  },
  {
    id: 52,
    name: 'MERC BRASIL',
    code: 'BMEB3',
    category: 'Financeiro',
    value: 14,
  },
  {
    id: 53,
    name: 'BANCO BMG',
    code: 'BMGB4',
    category: 'Financeiro',
    value: 42,
  },
  {
    id: 54,
    name: 'MERC INVEST',
    code: 'BMIN3',
    category: 'Financeiro',
    value: 36,
  },
  {
    id: 55,
    name: 'BIC MONARK',
    code: 'BMKS3',
    category: 'Consumo Cíclico',
    value: 4,
  },
  {
    id: 56,
    name: 'BEMOBI TECH',
    code: 'BMOB3',
    category: 'Tecnologia da Informação',
    value: 22,
  },
  {
    id: 57,
    name: 'NORD BRASIL',
    code: 'BNBR3',
    category: 'Financeiro',
    value: 45,
  },
  {
    id: 58,
    name: 'BOA VISTA',
    code: 'BOAS3',
    category: 'Financeiro',
    value: 6,
  },
  {
    id: 59,
    name: 'BOMBRIL',
    code: 'BOBR3',
    category: 'Consumo não Cíclico',
    value: 48,
  },
  {
    id: 60,
    name: 'BTGP BANCO',
    code: 'BPAC11',
    category: 'Financeiro',
    value: 15,
  },
];
